### PR TITLE
Crlf aware git credential

### PR DESCRIPTION
**Pull request by nyckyta**
Thanks for taking the time to contribute to Git!

Those seeking to contribute to the Git for Windows fork should see
http://gitforwindows.org/#contribute on how to contribute Windows specific
enhancements.

If your contribution is for the core Git functions and documentation
please be aware that the Git community does not use the github.com issues
or pull request mechanism for their contributions.

Instead, we use the Git mailing list (git@vger.kernel.org) for code and
documenatation submissions, code reviews, and bug reports. The
mailing list is plain text only (anything with HTML is sent directly
to the spam folder).

Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
@nyckyta how does this PR relate to https://github.com/git/git/pull/710?

**Comment by nyckyta** [comment]
> @nyckyta how does this PR relate to [git#710](https://github.com/git/git/pull/710)?

This is changes in code and docs related to credentials according to mail messages from that PR. 

As I understand they advised to make some notes in docs regarding line ending and to fix the same line-ending issue in other credentials related code.

**Comment by nyckyta** [comment]
@dscho , well, what do you think?

**Comment by dscho** [comment]
> well, what do you think?

I _hoped_ to get a chance to review all of the changes in 8f309aeb, as [Junio had asked for](https://github.com/git/git/pull/710#issuecomment-586401561).

But truth be told, I simply won't have the time to do that :-( (I tried...)

**Comment by dscho** [comment]
@nyckyta I had to rebase the patches, to avoid merge conflicts with c03859a66525c6bdc5cd3c02b31f06cfdd80b595.

Thank you for working on this, and sorry to keep you waiting!

**Pull request closed without merging**
