### PR TITLE
git-svn test fixes

### PR DESCRIPTION
**Pull request by nalla**
I had to alter your patch a bit. `GetFileAttributesW` worked while `GetFileAttributes` did not. Was able to figure it out with `error("")` statements. Without `GetFileAttributesW` the `_wrmdir(wpnew)` call was never reached.

### CODE REVIEW

**Comment by dscho** [comment]
D'oh! I should have copy-pasted the code above the added lines ;-)

Two questions:
- I recall you had some more git-svn test fixes (you linked to a gist), could you include them in the first commit?
- Since we want to push this upstream ASAP, and Junio – the Git maintainer – likes things orderly, could you prefix the first lines of the commit messages with a `mingw: ` prefix?

Thanks!

**Comment by dscho** [comment]
Oh, completely forgot to say: the changes look really well crafted.

**Comment by nalla** [comment]
> I recall you had some more git-svn test fixes
I already included them in the first place.

**Comment by dscho** [comment]
Thanks so much!

**Pull request merged**
